name: First Pipeline
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_DATABASE: posts-test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping"
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: |
          cd api
          cp .env.ci .env
      - name: Install Dependencies
        run: |
          cd api
          composer install -q --no-ansi --no-interaction --no-progress --no-scripts
      - name: Generate Application Key
        run: | 
          cd api
          php artisan key:generate
      - name: Directory Permission
        run: |
          cd api
          chmod -R 755 storage bootstrap/cache
      - name: phpstan
        run: |
          cd api
          ./vendor/bin/phpstan analyse --memory-limit=1G app/
      - name: phpinsights
        run: |
          cd api
          php artisan insights --no-interaction \
            --min-quality=90 --min-complexity=80 \
            --min-architecture=90 --min-style=90 \
            --ansi --format=github-action
      - name: Run tests
        run: |
          cd api
          php artisan test